CREATE TABLE inspection_data_eagle (
    date TIMESTAMP NOT NULL,
    rej TEXT,
    warn TEXT,
    op TEXT,
    action TEXT,
    thick DOUBLE PRECISION,
    type INTEGER,
    wid DOUBLE PRECISION,
    w_cor DOUBLE PRECISION,
    len DOUBLE PRECISION,
    l_cor DOUBLE PRECISION,
    sq DOUBLE PRECISION,
    sk DOUBLE PRECISION,
    cang_1 DOUBLE PRECISION,
    cang_2 DOUBLE PRECISION,
    cang_3 DOUBLE PRECISION,
    cang_4 DOUBLE PRECISION,
    defect DOUBLE PRECISION,
    thresh INTEGER,
    plc_w DOUBLE PRECISION,
    plc_l DOUBLE PRECISION,
    w_dev DOUBLE PRECISION,
    l_dev DOUBLE PRECISION,
    ang_1 DOUBLE PRECISION,
    ang_2 DOUBLE PRECISION,
    ang_3 DOUBLE PRECISION,
    ang_4 DOUBLE PRECISION,
    del_1 DOUBLE PRECISION,
    del_2 DOUBLE PRECISION,
    del_3 DOUBLE PRECISION,
    del_4 DOUBLE PRECISION,
    ink_x DOUBLE PRECISION,
    ink_y DOUBLE PRECISION,
    qual INTEGER,
    grpid INTEGER,
    pltid INTEGER,
    stream INTEGER,
    split INTEGER,
    head_cross_cut INTEGER,
    tail_cross_cut INTEGER,
    long_cut INTEGER,
    dest TEXT,
    align0 INTEGER,
    skew0 INTEGER,
    align1 INTEGER,
    skew1 INTEGER,
    cpu DOUBLE PRECISION,
    cpu_pk DOUBLE PRECISION,
    avail_ram INTEGER,
    total_mem INTEGER,
    avail_mem INTEGER,
    process_mem INTEGER,
    defect_x DOUBLE PRECISION,
    defect_y DOUBLE PRECISION,
    headx_cutb INTEGER,
    headx_cuth INTEGER,
    tailx_cutb INTEGER,
    tailx_cuth INTEGER,
    lefty_cutb INTEGER,
    lefty_cuth INTEGER,
    righty_cutb INTEGER,
    righty_cuth INTEGER
    UNIQUE(pltid,date)
) PARTITION BY RANGE (date);

